const permission = {
  "post:create": "Create a new post",
  "post:delete": "Delete all posts including other authors' posts",
  "post:publish": "Publish a waiting blog",
  "post:view": "View posts from all authors",
  "post:list": "List all posts",
  "tag:list": "View tag list",
  "tag:view": "View tag details",
  "tag:create": "Create new tags",
  "tag:update": "Update existing tags",
  "tag:delete": "Delete tags",
  "category:list": "View category list",
  "category:view": "View category details",
  "category:create": "Create new categories",
  "category:update": "Update existing categories",
  "category:delete": "Delete categories",
  "user:list": "View user list",
  "user:view": "View user details",
  "user:register": "Register a new user",
  "user:update": "Update a user's info",
  "user:delete": "Delete a user account",
  "user:change_passphrase": "Change another user's passphrase",
  "user:assign_role": "Assign a role to a user",
  "statistics:view-total": "View total statistics",
  "statistics:view-others": "View other users' statistics",
  "statistics:view-self": "View own statistics",
  "auditlog:view": "Inspect server audit logs",
};

export default permission;
